In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.pandas.set_option('display.max_columns', None)

In [41]:
df=pd.read_csv('House_price.csv')
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
df.shape   #rows and columns

(1460, 81)

In [42]:
df.describe()      # describes count, mean,std....

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1379.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,46.549315,567.240411,1057.429452,1162.626712,346.992466,5.844521,1515.463699,0.425342,0.057534,1.565068,0.382877,2.866438,1.046575,6.517808,0.613014,1978.506164,1.767123,472.980137,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,161.319273,441.866955,438.705324,386.587738,436.528436,48.623081,525.480383,0.518911,0.238753,0.550916,0.502885,0.815778,0.220338,1.625393,0.644666,24.689725,0.747315,213.804841,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,0.000000,0.000000,334.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,1900.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,0.000000,223.000000,795.750000,882.000000,0.000000,0.000000,1129.500000,0.000000,0.000000,1.000000,0.000000,2.000000,1.000000,5.000000,0.000000,1961.000000,1.000000,334.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,0.000000,477.500000,991.500000,1087.000000,0.000000,0.000000,1464.000000,0.000000,0.000000,2.000000,0.000000,3.000000,1.000000,6.000000,1.000000,1980.000000,2.000000,480.000000,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,0.000000,808.000000,1298.250000,1391.250000,728.000000,0.000000,1776.750000,1.000000,0.000000,2.000000,1.000000,3.000000,1.000000,7.000000,1.000000,2002.000000,2.000000,576.000000,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1474.000000,2336.000000,6110.000000,4692.000000,2065.000000,572.000000,5642.000000,3.000000,2.000000,3.000000,2.000000,8.000000,3.000000,14.000000,3.000000,2010.000000,4.000000,1418.000000,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [25]:
#check for null values
df.isnull().sum()     #isnull(). ... sum() returns the number of missing values in the data set.

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [47]:
df.isnull().sum()[df.isnull().sum()>0]

LotFrontage      259
Alley           1369
MasVnrType         8
MasVnrArea         8
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1453
Fence           1179
MiscFeature     1406
dtype: int64

In [27]:
drop_values=['Id','Alley','MiscFeature','PoolQC']
df.drop(drop_values,axis=1,inplace=True)         #When inplace = True , the data is modified in place
df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,3SsnPorch,ScreenPorch,PoolArea,Fence,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,3,65.0,8450,1,3,3,0,4,0,...,0,0,0,4,0,2,2008,8,4,208500
1,20,3,80.0,9600,1,3,3,0,2,0,...,0,0,0,4,0,5,2007,8,4,181500
2,60,3,68.0,11250,1,0,3,0,4,0,...,0,0,0,4,0,9,2008,8,4,223500
3,70,3,60.0,9550,1,0,3,0,0,0,...,0,0,0,4,0,2,2006,8,0,140000
4,60,3,84.0,14260,1,0,3,0,2,0,...,0,0,0,4,0,12,2008,8,4,250000

In [28]:
df.info()   #df.info() provides info of index dtype and column dtypes, non-null values and memory usage.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 77 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   int64
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   int64
 5   LotShape       1460 non-null   int64
 6   LandContour    1460 non-null   int64
 7   Utilities      1460 non-null   int64
 8   LotConfig      1460 non-null   int64
 9   LandSlope      1460 non-null   int64
 10  Neighborhood   1460 non-null   int64
 11  Condition1     1460 non-null   int64
 12  Condition2     1460 non-null   int64
 13  BldgType       1460 non-null   int64
 14  HouseStyle     1460 non-null   int64
 15  OverallQual    1460 non-null   int64
 16  OverallCond    1460 non-null   int64
 17  YearBuilt      1460 non-null   int64
 18  YearRemodAdd   1460 non-null   int64
 19  RoofStyle      1460 non-null   int64
 20  RoofMatl       1460 non-null   int64
 21  Exterior1st    1460 non-null   int64
 22  Exterior2nd    1460 non-null   int64
 23  MasVnrType     1460 non-null   int64
 24  MasVnrArea     1460 non-null   float64
 25  ExterQual      1460 non-null   int64
 26  ExterCond      1460 non-null   int64
 27  Foundation     1460 non-null   int64
 28  BsmtQual       1460 non-null   int64
 29  BsmtCond       1460 non-null   int64
 30  BsmtExposure   1460 non-null   int64
 31  BsmtFinType1   1460 non-null   int64
 32  BsmtFinSF1     1460 non-null   int64
 33  BsmtFinType2   1460 non-null   int64
 34  BsmtFinSF2     1460 non-null   int64
 35  BsmtUnfSF      1460 non-null   int64
 36  TotalBsmtSF    1460 non-null   int64
 37  Heating        1460 non-null   int64
 38  HeatingQC      1460 non-null   int64
 39  CentralAir     1460 non-null   int64
 40  Electrical     1460 non-null   int64
 41  1stFlrSF       1460 non-null   int64
 42  2ndFlrSF       1460 non-null   int64
 43  LowQualFinSF   1460 non-null   int64
 44  GrLivArea      1460 non-null   int64
 45  BsmtFullBath   1460 non-null   int64
 46  BsmtHalfBath   1460 non-null   int64
 47  FullBath       1460 non-null   int64
 48  HalfBath       1460 non-null   int64
 49  BedroomAbvGr   1460 non-null   int64
 50  KitchenAbvGr   1460 non-null   int64
 51  KitchenQual    1460 non-null   int64
 52  TotRmsAbvGrd   1460 non-null   int64
 53  Functional     1460 non-null   int64
 54  Fireplaces     1460 non-null   int64
 55  FireplaceQu    1460 non-null   int64
 56  GarageType     1460 non-null   int64
 57  GarageYrBlt    1379 non-null   float64
 58  GarageFinish   1460 non-null   int64
 59  GarageCars     1460 non-null   int64
 60  GarageArea     1460 non-null   int64
 61  GarageQual     1460 non-null   int64
 62  GarageCond     1460 non-null   int64
 63  PavedDrive     1460 non-null   int64
 64  WoodDeckSF     1460 non-null   int64
 65  OpenPorchSF    1460 non-null   int64
 66  EnclosedPorch  1460 non-null   int64
 67  3SsnPorch      1460 non-null   int64
 68  ScreenPorch    1460 non-null   int64
 69  PoolArea       1460 non-null   int64
 70  Fence          1460 non-null   int64
 71  MiscVal        1460 non-null   int64
 72  MoSold         1460 non-null   int64
 73  YrSold         1460 non-null   int64
 74  SaleType       1460 non-null   int64
 75  SaleCondition  1460 non-null   int64
 76  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(74)
memory usage: 878.4 KB

In [29]:
df['LotFrontage'].fillna(df['LotFrontage'].median(),inplace=True)
df['MasVnrArea'].fillna(df['MasVnrArea'].median(),inplace=True)
df['GarageYrBlt'].fillna(df['GarageYrBlt'].median(),inplace=True)

In [30]:
C_feat=df.select_dtypes(include = "object").columns

from sklearn.preprocessing import LabelEncoder     
le=LabelEncoder()
for feature in C_feat:
  df[feature]=le.fit_transform(df[feature].astype(str))
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 77 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   int64
 2   LotFrontage    1460 non-null   float64
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   int64
 5   LotShape       1460 non-null   int64
 6   LandContour    1460 non-null   int64
 7   Utilities      1460 non-null   int64
 8   LotConfig      1460 non-null   int64
 9   LandSlope      1460 non-null   int64
 10  Neighborhood   1460 non-null   int64
 11  Condition1     1460 non-null   int64
 12  Condition2     1460 non-null   int64
 13  BldgType       1460 non-null   int64
 14  HouseStyle     1460 non-null   int64
 15  OverallQual    1460 non-null   int64
 16  OverallCond    1460 non-null   int64
 17  YearBuilt      1460 non-null   int64
 18  YearRemodAdd   1460 non-null   int64
 19  RoofStyle      1460 non-null   int64
 20  RoofMatl       1460 non-null   int64
 21  Exterior1st    1460 non-null   int64
 22  Exterior2nd    1460 non-null   int64
 23  MasVnrType     1460 non-null   int64
 24  MasVnrArea     1460 non-null   float64
 25  ExterQual      1460 non-null   int64
 26  ExterCond      1460 non-null   int64
 27  Foundation     1460 non-null   int64
 28  BsmtQual       1460 non-null   int64
 29  BsmtCond       1460 non-null   int64
 30  BsmtExposure   1460 non-null   int64
 31  BsmtFinType1   1460 non-null   int64
 32  BsmtFinSF1     1460 non-null   int64
 33  BsmtFinType2   1460 non-null   int64
 34  BsmtFinSF2     1460 non-null   int64
 35  BsmtUnfSF      1460 non-null   int64
 36  TotalBsmtSF    1460 non-null   int64
 37  Heating        1460 non-null   int64
 38  HeatingQC      1460 non-null   int64
 39  CentralAir     1460 non-null   int64
 40  Electrical     1460 non-null   int64
 41  1stFlrSF       1460 non-null   int64
 42  2ndFlrSF       1460 non-null   int64
 43  LowQualFinSF   1460 non-null   int64
 44  GrLivArea      1460 non-null   int64
 45  BsmtFullBath   1460 non-null   int64
 46  BsmtHalfBath   1460 non-null   int64
 47  FullBath       1460 non-null   int64
 48  HalfBath       1460 non-null   int64
 49  BedroomAbvGr   1460 non-null   int64
 50  KitchenAbvGr   1460 non-null   int64
 51  KitchenQual    1460 non-null   int64
 52  TotRmsAbvGrd   1460 non-null   int64
 53  Functional     1460 non-null   int64
 54  Fireplaces     1460 non-null   int64
 55  FireplaceQu    1460 non-null   int64
 56  GarageType     1460 non-null   int64
 57  GarageYrBlt    1460 non-null   float64
 58  GarageFinish   1460 non-null   int64
 59  GarageCars     1460 non-null   int64
 60  GarageArea     1460 non-null   int64
 61  GarageQual     1460 non-null   int64
 62  GarageCond     1460 non-null   int64
 63  PavedDrive     1460 non-null   int64
 64  WoodDeckSF     1460 non-null   int64
 65  OpenPorchSF    1460 non-null   int64
 66  EnclosedPorch  1460 non-null   int64
 67  3SsnPorch      1460 non-null   int64
 68  ScreenPorch    1460 non-null   int64
 69  PoolArea       1460 non-null   int64
 70  Fence          1460 non-null   int64
 71  MiscVal        1460 non-null   int64
 72  MoSold         1460 non-null   int64
 73  YrSold         1460 non-null   int64
 74  SaleType       1460 non-null   int64
 75  SaleCondition  1460 non-null   int64
 76  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(74)
memory usage: 878.4 KB

In [31]:
C_feat

Index([], dtype='object')

In [32]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.preprocessing import StandardScaler

In [33]:
X = df.drop(['SalePrice'], axis = 1)
y = df.loc[:,['SalePrice']].values
sc=StandardScaler()
X=sc.fit_transform(X)
y=y.reshape(-1)

In [43]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [44]:
clf=LinearRegression()
reg=clf.fit(X_train, y_train)
predictions = reg.predict(X_test)
print('MSE : ',mean_squared_error(y_test,predictions))
print('R2_score:',r2_score(y_test,predictions))

MSE :  2455336514.7352424
R2_score: 0.6280873279218977

In [45]:
output=pd.DataFrame([y_test,predictions],index=['REAL' ,'PREDICTED'])
output.transpose()

         REAL      PREDICTED
0    200624.0  216173.118522
1    133000.0  174050.243522
2    110000.0   97952.368522
3    192000.0  216559.118522
4     88000.0   93927.618522
..        ...            ...
360  325000.0  258229.118522
361  178000.0  187120.118522
362  235000.0  240314.118522
363  239000.0  230714.618522
364   85000.0  109977.618522

[365 rows x 2 columns]

In [37]:
grid={}

Ridge Regression is a technique for analyzing multiple regression data that suffer from multicollinearity.
Grid-searching will build a model on each parameter combination possible.
Repeated k-fold cross-validation provides a way to improve the estimated performance of a machine learning model.
n_splitsint. Returns the number of splitting iterations in the cross-validator.

In [38]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedKFold
cv=RepeatedKFold(n_splits=20,n_repeats=5,random_state=1)
grid=dict()
grid['alpha']=np.arange(0,1,0.1)
ridge=Ridge()
ridge_reg=GridSearchCV(ridge,grid,scoring='neg_mean_absolute_error',cv=cv,n_jobs=-1)
ridge_reg.fit(X,y)

GridSearchCV(cv=RepeatedKFold(n_repeats=5, n_splits=20, random_state=1),
             estimator=Ridge(), n_jobs=-1,
             param_grid={'alpha': array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])},
             scoring='neg_mean_absolute_error')

In [39]:
ridge_pred=ridge_reg.predict(X_test)
print('r2_score of RIDGE REGREESOR :',r2_score(y_test,ridge_pred)*100)

r2_score of RIDGE REGREESOR : 80.4448280990222